name: Verify and update my version

on:
  release:
    types: [released]

jobs:
  verify-and-update-version:
    runs-on: ubuntu-latest

    # You have to grant content:write permissions to this job in order to update
    # the major version tag.
    permissions:
      contents: write

    steps:
      - name: Verify and update version
        uses: colinparsonsme/verify-and-update-version@v1
